services:
    astrology:
        build: .
        container_name: astrology-local
        restart: unless-stopped
        ports:
            - '8000:8000'
        volumes:
            - ./ephe:/opt/swisseph/ephe:ro
        environment:
            - EPH_PATH=/opt/swisseph/ephe
            - PYTHONPATH=/app
            - PYTHONUNBUFFERED=1
            - HOST=0.0.0.0
            - PORT=8000
        healthcheck:
            test: ['CMD', 'curl', '-f', 'http://localhost:8000/health']
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 40s
