version: '3.9'

services:
    astrology:
        build: .
        container_name: astrology-app
        restart: unless-stopped
        ports:
            - '8000:8000'
        volumes:
            - ./ephe:/opt/swisseph/ephe:ro # monta efemérides dentro del contenedor
            - astrology_logs:/app/logs # logs persistentes
        environment:
            - EPH_PATH=/opt/swisseph/ephe
            - PYTHONPATH=/app
            - PYTHONUNBUFFERED=1
            - HOST=0.0.0.0
            - PORT=8000
        networks:
            - astrology-network
        healthcheck:
            test: ['CMD', 'curl', '-f', 'http://localhost:8000/health']
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 40s

    # Opcional: Nginx como proxy reverso
    nginx:
        image: nginx:alpine
        container_name: astrology-nginx
        restart: unless-stopped
        ports:
            - '80:80'
            - '443:443'
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
            - ./ssl:/etc/nginx/ssl:ro # para certificados SSL
        depends_on:
            - astrology
        networks:
            - astrology-network

volumes:
    astrology_logs:

networks:
    astrology-network:
        driver: bridge
